#pragma once
//
// icm42688.hpp
//
// Minimal C++ SPI driver for the TDK InvenSense ICM-42688-P 6-axis IMU
// (3-axis gyroscope + 3-axis accelerometer), targeting an STM32F446RE
// (Nucleo-F446RE) via the STM32 HAL SPI driver generated by STM32CubeIDE.
//
// Written from scratch against the public ICM-42688-P datasheet
// (DS-000347). Register addresses and sensitivities below are cited from
// that datasheet; the sensor's power-on configuration sequence (WHO_AM_I
// check -> PWR_MGMT0 -> GYRO_CONFIG0/ACCEL_CONFIG0) follows InvenSense's
// documented bring-up order.
//
// Wiring (SPI mode 0, up to 24 MHz per datasheet):
//   Nucleo SPI1 SCK  -> ICM-42688 SCLK
//   Nucleo SPI1 MISO -> ICM-42688 SDO/AD0
//   Nucleo SPI1 MOSI -> ICM-42688 SDI
//   Any free GPIO    -> ICM-42688 /CS   (pass its port/pin to the constructor)
//
// This file has no dependency beyond the STM32 HAL SPI/GPIO API, so it
// compiles as ordinary C++17 once linked against a CubeIDE-generated
// stm32f4xx_hal.h.

#include <cstdint>
#include "stm32f4xx_hal.h"

namespace icm42688 {

struct MotionData {
    float accelX = 0.0f, accelY = 0.0f, accelZ = 0.0f; // g
    float gyroX  = 0.0f, gyroY  = 0.0f, gyroZ  = 0.0f;  // deg/s
    float temperatureC = 0.0f;
};

class Icm42688 {
public:
    // hspi must already be initialised by CubeMX (SPI, mode 0, <=24 MHz).
    // csPort/csPin identify the GPIO driving the sensor's /CS line.
    Icm42688(SPI_HandleTypeDef* hspi, GPIO_TypeDef* csPort, uint16_t csPin);

    // Resets the SPI framing, verifies WHO_AM_I (must read back 0x47),
    // and brings the gyro + accel into Low Noise mode at their widest
    // full-scale ranges (+-2000 dps / +-16 g) at 1 kHz ODR.
    // Returns false if WHO_AM_I doesn't match -- callers should treat that
    // as "sensor not present / miswired" and not proceed to read().
    bool begin();

    // Reads accel + gyro (12 contiguous data bytes, auto-incrementing on
    // the sensor side) plus the die temperature, and converts to physical
    // units. Returns false if begin() has not succeeded yet.
    bool read(MotionData& out);

    bool isInitialised() const { return initialised_; }

private:
    uint8_t readRegister(uint8_t reg);
    void    writeRegister(uint8_t reg, uint8_t value);
    void    readRegisters(uint8_t startReg, uint8_t* buffer, uint16_t length);

    void csLow();
    void csHigh();

    SPI_HandleTypeDef* hspi_;
    GPIO_TypeDef* csPort_;
    uint16_t csPin_;
    bool initialised_ = false;

    // --- Register addresses (ICM-42688-P datasheet DS-000347, Bank 0) ---
    static constexpr uint8_t kWhoAmIReg       = 0x75;
    static constexpr uint8_t kWhoAmIExpected  = 0x47;
    static constexpr uint8_t kPwrMgmt0Reg     = 0x4E;
    static constexpr uint8_t kGyroConfig0Reg  = 0x4F;
    static constexpr uint8_t kAccelConfig0Reg = 0x50;
    static constexpr uint8_t kAccelDataX1Reg  = 0x1F; // 12 bytes: accel(6)+gyro(6)
    static constexpr uint8_t kTempDataReg     = 0x1D; // 2 bytes
    static constexpr uint8_t kDirRead         = 0x80; // MSB set = read (SPI framing)

    // PWR_MGMT0 (0x4E): bits[3:2]=GYRO_MODE, bits[1:0]=ACCEL_MODE.
    // 0x0F = Gyro Low-Noise + Accel Low-Noise.
    // Double-check against DS-000347 section 14.36 before relying on this
    // in anything beyond a demo -- exact bit tables are worth re-verifying
    // against your own datasheet copy.
    static constexpr uint8_t kPwrGyroLnAccelLn = 0x0F;

    // GYRO_CONFIG0 / ACCEL_CONFIG0: FS_SEL in bits[7:5], ODR in bits[3:0].
    // 0x06 selects the widest full-scale range (+-2000dps / +-16g) at
    // 1 kHz ODR. Cross-check against DS-000347 sections 14.37/14.38.
    static constexpr uint8_t kGyroFs2000Odr1k = 0x06;
    static constexpr uint8_t kAccelFs16gOdr1k  = 0x06;

    // --- Sensitivities at the ranges configured above (datasheet Table) ---
    static constexpr float kAccelSensitivityLsbPerG  = 2048.0f; // @ +-16g
    static constexpr float kGyroSensitivityLsbPerDps = 16.4f;   // @ +-2000dps
    static constexpr float kTempSensitivityLsbPerC   = 132.48f;
    static constexpr float kTempOffsetC              = 25.0f;
};

} // namespace icm42688
